### ISSUE TITLE
DOMImplementation::getFeature() is undocumented

### ISSUE THREAD

**Issue by WinterSilence** [php/doc-en#820]
From manual page: https://php.net/class.domimplementation

---
`ReflectionClass` detect method `getFeature()` missed in [manual](https://www.php.net/class.domimplementation):
~~~
Method [  public method getFeature ] {
  - Parameters [2] {
    Parameter #0 [  $feature ]
    Parameter #1 [  $version ]
  }
}
~~~
`ReflectionMethod` not detect `hasFeature()` parameters: 
~~~
Method [  public method hasFeature ] {
  - Parameters [0] {
  }
}
~~~
but in manual:
`public hasFeature(string $feature, string $version): bool`

**Comment by cmb69** [comment]
The `::getFeature()` documentatation is indeed missing, but the signature of `::hasFeature()` is correct (reflection is wrong for PHP 7.4, what has been fixed for PHP 8).

**Comment by WinterSilence** [comment]
@cmb69 I use PHP **7.3**, why not fix it in 7.x too?

**Comment by cmb69** [comment]
PHP 7.3 is [no longer actively supported](https://www.php.net/supported-versions.php), so won't receive bug fixes; fixing this for PHP 7.4 would constitute a BC break.

**Comment by WinterSilence** [comment]
@cmb69 doesn't fix in PHP 8 break BC? I think any bugfix can't be BC.

**Comment by cmb69** [comment]
> doesn't fix in PHP 8 break BC?

Yes, but some BC breaks are allowed in a major version.
